---
- name: Reiniciar apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: restarted
  when: ansible_os_family != 'Windows'

- name: Recargar apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: reloaded
  when: ansible_os_family != 'Windows'

- name: Reiniciar apache Windows
  ansible.windows.win_service:
    name: "{{ apache_service_name_windows }}"
    state: restarted
  when: ansible_os_family == 'Windows'
