---
- name: Verificar que el rol apache solo se ejecuta en Linux
  ansible.builtin.fail:
    msg: "El rol apache solo está soportado en Linux. En Windows usa IIS."
  when: ansible_os_family == "Windows"

- name: Incluir tareas Linux
  ansible.builtin.include_tasks:
    file: linux.yml
