---
- name: Reiniciar mariadb
  ansible.builtin.service:
    name: "{{ mariadb_service_name }}"
    state: restarted
  when: ansible_os_family != 'Windows'

- name: Reiniciar mariadb Windows
  ansible.windows.win_service:
    name: "{{ mariadb_service_name_windows }}"
    state: restarted
  when: ansible_os_family == 'Windows'
