---
- name: Recargar nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: ansible_os_family != 'Windows'

- name: Reiniciar nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: ansible_os_family != 'Windows'

- name: Recargar nginx Windows
  ansible.windows.win_service:
    name: nginx
    state: restarted
  when: ansible_os_family == 'Windows'
