---
- name: Asegurar que Chocolatey está instalado
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present

- name: Instalar paquetes base (Windows)
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ common_packages_windows }}"
    state: present

- name: Configurar zona horaria (Windows)
  community.windows.win_timezone:
    timezone: "{{ timezone_windows }}"

- name: Asegurar que el servicio Windows Time está activo
  ansible.windows.win_service:
    name: w32tm
    start_mode: auto
    state: started

- name: Sincronizar reloj con servidor NTP (Windows)
  ansible.windows.win_shell: |
    w32tm /config /manualpeerlist:"{{ common_ntp_servers_windows | join(' ') }}" /syncfromflags:manual /reliable:YES /update
    w32tm /resync /force
  changed_when: false
