---
- name: Instalar Docker y desplegar contenedores
  hosts: "{{ target_hosts | default('all') }}"
  become: true

  roles:
    - role: docker_install
    - role: docker_daemon
    - role: docker_network
    - role: docker_volume
    - role: docker_container
